// Generated by gencpp from file jason_msgs/ActionStatus.msg
// DO NOT EDIT!


#ifndef JASON_MSGS_MESSAGE_ACTIONSTATUS_H
#define JASON_MSGS_MESSAGE_ACTIONSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace jason_msgs
{
template <class ContainerAllocator>
struct ActionStatus_
{
  typedef ActionStatus_<ContainerAllocator> Type;

  ActionStatus_()
    : header()
    , result(false)
    , id(0)  {
    }
  ActionStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , result(false)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _result_type;
  _result_type result;

   typedef uint32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::jason_msgs::ActionStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jason_msgs::ActionStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ActionStatus_

typedef ::jason_msgs::ActionStatus_<std::allocator<void> > ActionStatus;

typedef boost::shared_ptr< ::jason_msgs::ActionStatus > ActionStatusPtr;
typedef boost::shared_ptr< ::jason_msgs::ActionStatus const> ActionStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jason_msgs::ActionStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jason_msgs::ActionStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jason_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'jason_msgs': ['/root/jason-ros/jason_ws/src/jason_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jason_msgs::ActionStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jason_msgs::ActionStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jason_msgs::ActionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jason_msgs::ActionStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jason_msgs::ActionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jason_msgs::ActionStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jason_msgs::ActionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd2ff4c1c257386dae20268cf70a828d";
  }

  static const char* value(const ::jason_msgs::ActionStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd2ff4c1c257386dULL;
  static const uint64_t static_value2 = 0xae20268cf70a828dULL;
};

template<class ContainerAllocator>
struct DataType< ::jason_msgs::ActionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jason_msgs/ActionStatus";
  }

  static const char* value(const ::jason_msgs::ActionStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jason_msgs::ActionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool result\n\
uint32 id\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::jason_msgs::ActionStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jason_msgs::ActionStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.result);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jason_msgs::ActionStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jason_msgs::ActionStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JASON_MSGS_MESSAGE_ACTIONSTATUS_H
